# Generated by Django 2.2 on 2019-04-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
