# Generated by Django 2.2 on 2019-04-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovedo'), (2, 'Cancelado')], default=1, verbose_name='Situação'),
        ),
    ]
